---
title: "Untitled"
author: "BoRistats"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(tidyverse)
```

```{r}
source('~/Research/periodiQ/R/fct_simulation.R')
res <- simulate_queue(params = scenario_params())
```

```{r}
#' make html code of model info for the chosen parameters
#'
#' @param params parameters
#' @param digits number of digits to round to (default = 3)
#'
#' @return
#' @export
#'
#' @examples
model_info_html <- function(params, digits = 3) {
  eta <- params$eta
  s <- params$s
  mu <- params$mu
  gamma <- params$gamma
  lambda_0 <- params$lambda_0
  rates <- lambda_0 + c(0, gamma / 2, gamma)
  names(rates) <- c("min", "ave", "max")
  rhos <- rates * eta / (s * mu)
  # round for nicer output:
  rhos <- round(rhos, digits = digits)
  sentence1 <-
    paste0("The average rate is ",
           rates[2],
           " and the range is ",
           rates[1],
           " - ",
           rates[3],
           ".")
  sentence2 <-
    paste0("Thus the offered load is on average ",
           rhos[2],
           " and ranges ",
           rhos[1],
           " - ",
           rhos[3],
           ".")
  rho_text <- paste(sentence1, sentence2, sep = "\n")


  params_round <- sapply(params, round, digits = digits)
  human_text <- with(params,  {
    sentence1 <-
      paste0(
        "The customers' patience is exponentially distributed with parameter: ",
        theta,
        " (mean = ",
        round(1 / theta, digits  = 3),
        ")"
      )

    jobsize_distr <- paste0("Gamma(", eta, ", ", mu, ")")
    sentence2 <-
      paste0(
        "The job sizes are independent of the patience and distributed ",
        jobsize_distr,
        " (mean = ",
        round(eta / mu, digits = digits),
        "). "
      ) # average jobsize

    sentence3 <-
      paste0(
        "This implies that customers are willing to wait ",
        100 * (1 / theta) / (eta / mu),
        "%",
        " of their job requirement, on average"
      )




  # the human text:
  paste(sentence1, sentence2, sentence3, sep = "\n")
}
  )
  txt <- paste0('<div> ', c(rho_text,human_text), '</div>')
    return(txt)

}
```


```{r}
# first column - instructions
col1_script <- '
  <div class="column">
   <p>This section produces simulations of the process with parameter settings of your choice.</p>

              <p>Change parameters by clicking the configuration button below <svg aria-hidden="true" role="img" viewBox="0 0 640 512" style="height:1em;width:1.25em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M512.1 191l-8.2 14.3c-3 5.3-9.4 7.5-15.1 5.4-11.8-4.4-22.6-10.7-32.1-18.6-4.6-3.8-5.8-10.5-2.8-15.7l8.2-14.3c-6.9-8-12.3-17.3-15.9-27.4h-16.5c-6 0-11.2-4.3-12.2-10.3-2-12-2.1-24.6 0-37.1 1-6 6.2-10.4 12.2-10.4h16.5c3.6-10.1 9-19.4 15.9-27.4l-8.2-14.3c-3-5.2-1.9-11.9 2.8-15.7 9.5-7.9 20.4-14.2 32.1-18.6 5.7-2.1 12.1.1 15.1 5.4l8.2 14.3c10.5-1.9 21.2-1.9 31.7 0L552 6.3c3-5.3 9.4-7.5 15.1-5.4 11.8 4.4 22.6 10.7 32.1 18.6 4.6 3.8 5.8 10.5 2.8 15.7l-8.2 14.3c6.9 8 12.3 17.3 15.9 27.4h16.5c6 0 11.2 4.3 12.2 10.3 2 12 2.1 24.6 0 37.1-1 6-6.2 10.4-12.2 10.4h-16.5c-3.6 10.1-9 19.4-15.9 27.4l8.2 14.3c3 5.2 1.9 11.9-2.8 15.7-9.5 7.9-20.4 14.2-32.1 18.6-5.7 2.1-12.1-.1-15.1-5.4l-8.2-14.3c-10.4 1.9-21.2 1.9-31.7 0zm-10.5-58.8c38.5 29.6 82.4-14.3 52.8-52.8-38.5-29.7-82.4 14.3-52.8 52.8zM386.3 286.1l33.7 16.8c10.1 5.8 14.5 18.1 10.5 29.1-8.9 24.2-26.4 46.4-42.6 65.8-7.4 8.9-20.2 11.1-30.3 5.3l-29.1-16.8c-16 13.7-34.6 24.6-54.9 31.7v33.6c0 11.6-8.3 21.6-19.7 23.6-24.6 4.2-50.4 4.4-75.9 0-11.5-2-20-11.9-20-23.6V418c-20.3-7.2-38.9-18-54.9-31.7L74 403c-10 5.8-22.9 3.6-30.3-5.3-16.2-19.4-33.3-41.6-42.2-65.7-4-10.9.4-23.2 10.5-29.1l33.3-16.8c-3.9-20.9-3.9-42.4 0-63.4L12 205.8c-10.1-5.8-14.6-18.1-10.5-29 8.9-24.2 26-46.4 42.2-65.8 7.4-8.9 20.2-11.1 30.3-5.3l29.1 16.8c16-13.7 34.6-24.6 54.9-31.7V57.1c0-11.5 8.2-21.5 19.6-23.5 24.6-4.2 50.5-4.4 76-.1 11.5 2 20 11.9 20 23.6v33.6c20.3 7.2 38.9 18 54.9 31.7l29.1-16.8c10-5.8 22.9-3.6 30.3 5.3 16.2 19.4 33.2 41.6 42.1 65.8 4 10.9.1 23.2-10 29.1l-33.7 16.8c3.9 21 3.9 42.5 0 63.5zm-117.6 21.1c59.2-77-28.7-164.9-105.7-105.7-59.2 77 28.7 164.9 105.7 105.7zm243.4 182.7l-8.2 14.3c-3 5.3-9.4 7.5-15.1 5.4-11.8-4.4-22.6-10.7-32.1-18.6-4.6-3.8-5.8-10.5-2.8-15.7l8.2-14.3c-6.9-8-12.3-17.3-15.9-27.4h-16.5c-6 0-11.2-4.3-12.2-10.3-2-12-2.1-24.6 0-37.1 1-6 6.2-10.4 12.2-10.4h16.5c3.6-10.1 9-19.4 15.9-27.4l-8.2-14.3c-3-5.2-1.9-11.9 2.8-15.7 9.5-7.9 20.4-14.2 32.1-18.6 5.7-2.1 12.1.1 15.1 5.4l8.2 14.3c10.5-1.9 21.2-1.9 31.7 0l8.2-14.3c3-5.3 9.4-7.5 15.1-5.4 11.8 4.4 22.6 10.7 32.1 18.6 4.6 3.8 5.8 10.5 2.8 15.7l-8.2 14.3c6.9 8 12.3 17.3 15.9 27.4h16.5c6 0 11.2 4.3 12.2 10.3 2 12 2.1 24.6 0 37.1-1 6-6.2 10.4-12.2 10.4h-16.5c-3.6 10.1-9 19.4-15.9 27.4l8.2 14.3c3 5.2 1.9 11.9-2.8 15.7-9.5 7.9-20.4 14.2-32.1 18.6-5.7 2.1-12.1-.1-15.1-5.4l-8.2-14.3c-10.4 1.9-21.2 1.9-31.7 0zM501.6 431c38.5 29.6 82.4-14.3 52.8-52.8-38.5-29.6-82.4 14.3-52.8 52.8z"/></svg>.</p>

              <p>Just hit the &quot;generate&quot; button to produce a new realization.</p>

              <p>Alternatively, you can use one of the large pre-generated datasets by hitting one of the scenario buttons.</p>

              <p>Descriptive analyses of the realization will be produced below after the simulation is over.</p>      
  </div>
'

# second column with model info
col2_script <- model_info_html(params = res$params)
col2 <- paste0(c(' <div class="column">',
         col2_script,
         "</div>"),collapse = "")
two_col_css <- '.row {
  display: flex;
}

.column {
  flex: 50%;
}'

tagList(
  tags$style(two_col_css),
  HTML('
    <div class="row">'),
  HTML(col1_script),
  HTML(col2),
  HTML("</div>")
)
  
  
      
```


```{r}



shinyWidgets::radioGroupButtons(
  inputId = "Id069",
  label = "Choose a graph :",
  choiceNames = list(div(fontawesome::fa("hourglass"),
                             h5("determistic")),
                     div(fontawesome::fa("random"),
                             h5("exponential"))),
  
  choiceValues = list("deterministic", "exponential"),justified = T
)



unlist((icon("hourglass",
   lib = "glyphicon")))
```

